# Generated by Django 5.2 on 2025-05-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(default='black,white', help_text='Comma-separated available colors', max_length=255),
        ),
    ]
