# Generated by Django 5.2 on 2025-05-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_available_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Комментарий администратора (причина отклонения)'),
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', help_text='Статус проверки дизайна администратором', max_length=20),
        ),
    ]
