# Generated by Django 5.2 on 2025-05-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_admin_feedback_product_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design_position',
            field=models.TextField(blank=True, help_text='JSON data for design position and size'),
        ),
        migrations.AddField(
            model_name='product',
            name='rendered_image',
            field=models.ImageField(blank=True, help_text='T-shirt with design applied', null=True, upload_to='products/rendered/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Original design image', upload_to='products/'),
        ),
    ]
