# Generated by Django 5.2 on 2025-05-13 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='rendered_image',
            field=models.ImageField(blank=True, help_text='Default rendered image (for backward compatibility)', null=True, upload_to='products/rendered/'),
        ),
        migrations.CreateModel(
            name='ProductRenderedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='T-shirt color', max_length=20)),
                ('image', models.ImageField(help_text='Rendered image for this color', upload_to='products/rendered/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendered_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Rendered Product Image',
                'verbose_name_plural': 'Rendered Product Images',
                'unique_together': {('product', 'color')},
            },
        ),
    ]
