# Alternative simpler configuration
[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install --break-system-packages -r requirements.txt']

[start]
cmd = 'gunicorn onerai.wsgi:application --bind 0.0.0.0:$PORT'
