[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['python3 manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn onerai.wsgi:application --bind 0.0.0.0:$PORT'
