[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
DJANGO_SETTINGS_MODULE = "onerai.settings_production"
PYTHONPATH = "/app"
